stateStores:
- kind: BucketStateStore
  name: default
  namespace: kratix-platform-system
  secretRef:
    name: rustfs-credentials
    values:
      accesskey: bWluaW9hZG1pbg==
      secretkey: bWluaW9hZG1pbg==
  insecure: true
  endpoint: rustfs.kratix-platform-system.svc.cluster.local
  bucket: kratix
