---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-platform-kratix-io-v1alpha1-promise
  failurePolicy: Fail
  name: mpromise.kb.io
  rules:
  - apiGroups:
    - platform.kratix.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - promises
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-platform-kratix-io-v1alpha1-destination
  failurePolicy: Fail
  name: vdestination.kb.io
  rules:
  - apiGroups:
    - platform.kratix.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - destinations
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-platform-kratix-io-v1alpha1-destination
  failurePolicy: Fail
  name: vdestination.kb.io
  rules:
  - apiGroups:
    - platform.kratix.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - destinations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-platform-kratix-io-v1alpha1-promise
  failurePolicy: Fail
  name: vpromise.kb.io
  rules:
  - apiGroups:
    - platform.kratix.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - promises
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-platform-kratix-io-v1alpha1-promiserelease
  failurePolicy: Fail
  name: vpromiserelease.kb.io
  rules:
  - apiGroups:
    - platform.kratix.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - promisereleases
  sideEffects: None
