apiVersion: platform.kratix.io/v1alpha1
kind: Promise
metadata:
  name: deployment
  namespace: default
spec:
  xaasCrd:
    apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    metadata:
      name: deployments.marketplace.kratix.io
    spec:
      group: marketplace.kratix.io
      names:
        kind: deployment
        plural: deployments
        singular: deployment
      scope: Namespaced
      versions:
        - name: v1alpha1
          schema:
            openAPIV3Schema:
              properties:
                spec:
                  properties:
                    image:
                      type: string
                    containsCreditCardData:
                      default: false
                      type: boolean
                    clusterSelectors:
                      description: |
                        List of key:value pairs to use as cluster selectors when scheduling
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                  type: object
              type: object
          served: true
          storage: true
  xaasRequestPipeline:
    - syntasso/demo-deployment-request-pipeline:v0.1.1
  clusterSelector:
    environment: dev
