labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: kratix-manager
    app.kubernetes.io/instance: kratix-platform
    app.kubernetes.io/part-of: kratix

# All RBAC will be applied under this service account in
# the deployment namespace. You may comment out this resource
# if your manager will use a service account that exists at
# runtime. Be sure to update RoleBinding and ClusterRoleBinding
# subjects if changing service account names.
resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml
- metrics_auth_role.yaml
- metrics_auth_role_binding.yaml
- metrics_reader_role.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# For each CRD, "Admin", "Editor" and "Viewer" roles are scaffolded by
# default, aiding admins in cluster management. Those roles are
# not used by the kratix itself. You can comment the following lines
# if you do not want those helpers be installed with your Project.
- promiserevision_admin_role.yaml
- promiserevision_editor_role.yaml
- promiserevision_viewer_role.yaml