kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31337
    hostPort: 31337
  - containerPort: 31333
    hostPort: 31333
  extraMounts:
  - hostPath: IMAGE_CACHE_DIR
    containerPath: /images
