apiVersion: v1
kind: ConfigMap
metadata:
  name: kratix
  namespace: kratix-platform-system
data:
  config: |
    workflows:
      jobOptions:
        defaultBackoffLimit: 4
      defaultContainerSecurityContext:
        windowsOptions:
          runAsUserName: "setInKratixConfig"
    telemetry:
      traces:
        enabled: true
      metrics:
        enabled: true
      endpoint: grafana-k8s-monitoring-alloy-receiver.default.svc.cluster.local:4317
      protocol: grpc
      insecure: true
    logging:
      structured: true
      level: info
