apiVersion: platform.kratix.io/v1alpha1
kind: Cluster
metadata:
  name: worker-cluster-1
  namespace: default
  labels:
    environment: dev
spec:
  stateStoreRef:
    name: default
    kind: BucketStateStore
