config:
  path: "destinations/dev/worker-1" # Path in StateStore. See https://kratix.io/docs/main/reference/destinations/intro
  namespace: "default" # Namespace to create config
  secretRef:
    name: "gitea-credentials" # Name of secret
  git:
    url: https://172.18.0.2:31333/gitea_admin/kratix
    branch: main
