on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: trigger-run-ci
        id: trigger-run-ci
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.1.0
        with:
          GHA_Meta: ${{ github.event.release.tag_name }}
          target-slug: ${{ secrets.CCI_TARGET_SLUG }}
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}