name: Release Kratix

on:
#  workflow_run:
#    workflows: [Test Kratix]
#    types: [completed]
#    branches: [main]
  push: # to get faster feedback; will revert back to what's above after the ci migration issue
    branches: [main]

jobs:
  tag-new-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out kratix
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.ACTION_PUSH }}
      - name: Tag new version
        env:
          LAST_SHA: ${{ steps.checkout.outputs.commit }}
        run: |
          latest_tag="latest"
          current_commit=${LAST_SHA:-$(git rev-parse HEAD)}
          commit_list=$(git rev-list "$latest_tag".."$current_commit")
          git config user.name "syntassodev"
          git config user.email "kratix@syntasso.io"
          echo "checking if there are new commits from main compared to the latest tag"
          if [ -n "$commit_list" ]; then
              echo "Current commit is ahead of the previous tag; pushing a new tag"
              git tag -a $latest_tag -m "${latest_tag}" --force
              git push origin $latest_tag --force
          else
              echo "Current commit is not ahead of the previous tag; not pushing a new tag"
          fi
  build-and-push-kratix-platform:
    runs-on: ubuntu-latest
    needs: [tag-new-version]
    steps:
      - name: Check out kratix
        uses: actions/checkout@v4
      - name: Docker login to GHCR
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Kratix Platform
        run: |
          make docker-build-and-push
  build-and-push-pipeline-adapter:
    runs-on: ubuntu-latest
    needs: [tag-new-version]
    steps:
      - name: Check out kratix
        uses: actions/checkout@v4
      - name: Docker login to GHCR
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Pipeline
        run: |
          make build-and-push-work-creator
  publish-release:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-kratix-platform
      - build-and-push-pipeline-adapter
    steps:
      - name: Check out kratix
        uses: actions/checkout@v4
        id: checkout
      - name: Checkout out kratix helm charts
        uses: actions/checkout@v4
        with:
          repository: syntasso/helm-charts
          path: charts
          ssh-key: ${{ secrets.HELM_REPO_SSH_KEY }}
      - name: Create Kratix Distribution and Helm Template
        run: |
          ./scripts/make-distribution
          ./charts/scripts/generate-templates-and-crds ./distribution/kratix.yaml
        env:
          VERSION: ${{ steps.checkout.outputs.commit }}
      - name: Create Github Release
        run: |
            gh config set prompt disabled
            gh release delete <<pipeline.git.tag>> || true
            gh release create <<pipeline.git.tag>> --title <<pipeline.git.tag>> ./distribution/**/*.yaml ./distribution/*.yaml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push-to-helm-charts
        run: |
          cd charts
          git add kratix/
          git diff --cached --quiet && exit 0 || true

          git commit -m"update kratix package"
          git push origin main
